apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airlines
  labels:
    app: airlines
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: airlines
  template:
    metadata:
      labels:
        app: airlines
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: airlines
        image: docker.io/fluxcapacitor/prediction-jvm:master
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 100Mi 
        imagePullPolicy: "Always"
        env:
        - name: PIO_MODEL_TYPE
          value: pmml 
        - name: PIO_MODEL_NAMESPACE
          value: default
        - name: PIO_MODEL_NAME
          value: pmml_airlines 
        - name: PIO_MODEL_VERSION
          value: v0
        ports:
        - containerPort: 9040
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://<user>:<token>@gitlab.com/shareactor/source.ml.git"
            revision: "dev"