apiVersion: v1
kind: Service
metadata:
  name: airlines
  labels:
    app: airlines
    hystrix.enabled: "true"
#    dns: route53
#  annotations:
#    domainName: "airlines.your.domain.com"
spec:
  type: LoadBalancer
  ports:
  - name: airlines
    port: 80 
    targetPort: 9040 
  selector:
    app: airlines
    hystrix.enabled: "true" 
